apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: edumeet
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: edumeet-server
          namespace: edumeet