apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: docker.io/kixelated/moq-js
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - "grep -lir relay.quic.video . | xargs sed -i 's/relay.quic.video/relay.moq.stunner.cc/g' && node ./web/dist/server/entry.mjs"
        ports:
        - containerPort: 4321
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4321
  selector:
    app: web
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moq-web
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Cross-Origin-Opener-Policy: same-origin";
      more_set_headers "Cross-Origin-Embedder-Policy: require-corp";
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - moq.stunner.cc
    secretName: moq.stunner.cc
  rules:
  - host: moq.stunner.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80