apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: jitsi
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: jitsi-jvb
          namespace: jitsi