apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: cloudretro
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: worker-ci-udp-svc
          namespace: cloudretro