apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: live-broadcaster
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: live-broadcaster
          namespace: live-broadcaster