#apiVersion: v1
#data:
#  api-token: add-your-api-key-by-hand
#kind: Secret
#metadata:
#  name: cloudflare-api-token-secret
#  namespace: cert-manager
#type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: info@l7mp.io
    preferredChain: ""
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
          email: info@l7mp.io
      selector:
        dnsZones:
        - global.stunner.cc
