apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kurento-magicmirror
  namespace: argocd
spec:
  destination:
    namespace: kurento-magicmirror
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./gcp-europe-central2/apps/kurento-magicmirror
    repoURL: https://github.com/l7mp/demo-clusters.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true