apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stunner-gateway-operator
spec:
  destination:
    name: ''
    namespace: stunner
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://l7mp.io/stunner'
    targetRevision: 0.15.0
    chart: stunner-gateway-operator
    helm:
      values: ""
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
