apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: neko
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: neko-udp
          namespace: neko