apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: livekit
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: livekit-server
          namespace: livekit