apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 7.3.11
    chart: argo-cd
    helm:
      values: |-
        global:
          domain: argocd.aks-poland-central.stunner.cc

        configs:
          params:
            server.insecure: true

        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              cert-manager.io/cluster-issuer: letsencrypt-prod
            extraTls:
            - hosts:
              - argocd.aks-poland-central.stunner.cc
              secretName: argocd-tls
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
