apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janus
  namespace: argocd
spec:
  destination:
    namespace: janus
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./aks-poland-central/apps/janus
    repoURL: https://github.com/l7mp/demo-clusters.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true