apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: kurento-one2one
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: kms
          namespace: kurento-one2one