apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: broadcaster
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - name: broadcaster
          namespace: broadcaster
