apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: janus
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
  rules:
    - backendRefs:
        - kind: Service
          name: janus-gateway
          namespace: janus