apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: jitsi-gatewayclass
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: "stunner.l7mp.io"
    kind: GatewayConfig
    name: jitsi-gatewayconfig
    namespace: jitsi
  description: "STUNner is a WebRTC ingress gateway for Kubernetes"
---
apiVersion: stunner.l7mp.io/v1alpha1
kind: GatewayConfig
metadata:
  name: jitsi-gatewayconfig
  namespace: jitsi
spec:
  realm: stunner.l7mp.io
  authType: longterm
  sharedSecret: "my-shared-secret"
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: jitsi-gateway
  namespace: jitsi
spec:
  gatewayClassName: jitsi-gatewayclass
  listeners:
    - name: default-listener
      port: 3477
      protocol: UDP
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: jitsi
  namespace: jitsi
spec:
  parentRefs:
    - name: jitsi-gateway
  rules:
    - backendRefs:
        - name: jitsi-jvb
          namespace: jitsi